#!/busybox sh
if [ ! -d /bin ]; then
    /busybox mkdir /bin
    /busybox --install -s /bin
fi

if [ ! -d /dev ]; then
    mkdir /dev
fi

if [ ! -e /dev/vdb ]; then
    mount -t devtmpfs none /dev
fi

if [ ! -e /output ]; then
    ln -s /dev/ttyS1 /output
fi

if [ -e /dev/vdb ]; then
    echo "Extracting rootfs.tar from /dev/vdb:"
    tar -xvf /dev/vdb
fi

if [ $1 == "--" ]; then
    shift;
fi

if [ $# -gt 0 ]; then
    echo "Running command: $@"
    $@;
else
    echo "No commands were specified as init arguments. Opening a shell..."
    sh
fi
