#!/busybox sh
if [ ! -d /bin ]; then
    /busybox mkdir /bin
    /busybox --install -s /bin
fi

if [ ! -d /dev ]; then
    mkdir /dev
fi

if [ ! -e /dev/vdb ]; then
    mount -t devtmpfs none /dev
fi

if [ ! -e /output ]; then
    ln -s /dev/ttyS1 /output
fi

if [ -e /dev/vdb ]; then
    echo "Extracting rootfs.tar from /dev/vdb:"
    tar -xvf /dev/vdb
fi

if [ -e /dev/sda ]; then
    echo "Mounting modules..."
    mkdir -p /mnt/modules
    mount -t ext4 /dev/sda /mnt/modules

    mkdir -p /lib
    if [ -d /mnt/modules/lib/modprobe.d ]; then ln -s /mnt/modules/lib/modprobe.d /lib/; fi
    if [ -d /mnt/modules/lib/modules ]; then
        ln -s /mnt/modules/lib/modules /lib/
        if [ ! -f /lib/modules/*/modules.dep ]; then
            echo "Running depmod (as modules.dep is missing)..."
            depmod
            sync # save file changes
        fi
    fi
fi

chmod o+rx / /bin /etc /dev /scripts

if [ $1 == "--" ]; then
    shift;
fi

if [ $# -gt 0 ]; then
    echo "Running command: $@"
    $@;
else
    echo "No commands were specified as init arguments. Opening a shell..."
    sh
fi
