#!/busybox sh
if [ ! -d /bin ]; then
    /busybox mkdir /bin
    /busybox --install -s /bin
fi

if [ ! -d /dev ]; then
    mkdir /dev
fi

mkdir -p /proc
mount proc /proc -t proc

mkdir -p /sys
mount -t sysfs sysfs /sys

if [ ! -e /output ]; then
    ln -s /dev/ttyS1 /output
fi

if [ ! -e /dev/vdb ]; then
    mount -t devtmpfs none /dev
fi

if [ -e /dev/vdb ]; then
    echo "Extracting rootfs.tar from /dev/vdb:"
    tar -xvf /dev/vdb
fi

if [ ! -z "$MOUNT_MODULES" ]; then
    echo "Mounting modules..."
    mkdir -p /mnt/modules
    mount -t ext4 "$MOUNT_MODULES" /mnt/modules

    mkdir -p /lib
    if [ -d /mnt/modules/lib/modprobe.d ]; then ln -s /mnt/modules/lib/modprobe.d /lib/; fi
    if [ -d /mnt/modules/lib/modules ]; then
        ln -s /mnt/modules/lib/modules /lib/
        if [ ! -f /lib/modules/*/modules.dep ]; then
            echo "Running depmod (as modules.dep is missing)..."
            depmod
            sync # save file changes
        fi
    fi
fi

if [ ! -z "$MOUNT_CUSTOM_MODULES" ]; then
    echo "Extracting custom modules from $MOUNT_CUSTOM_MODULES:"
    mkdir -p /custom_modules
    tar -xvf "$MOUNT_CUSTOM_MODULES" -C /custom_modules
fi

# disable LoadPin
for name in "enforce" "enabled"; do
    if [ -e "/proc/sys/kernel/loadpin/$name" ] && [ "$(cat /proc/sys/kernel/loadpin/$name)" != "0" ]; then
        echo 0 > "/proc/sys/kernel/loadpin/$name";
    fi
done

for MODULE_FN in $(find /custom_modules -name '*.ko' 2>/dev/null); do
    echo "Loading custom module: $MODULE_FN"
    insmod $MODULE_FN
done

chmod o+rx / /bin /etc /dev /scripts

if [ "$1" == "--" ]; then
    shift;
fi

if [ $# -gt 0 ]; then
    echo "Running command: $@"
    eval "$@"
else
    echo "No commands were specified as init arguments. Opening a shell..."
    sh
fi
