# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Run daily tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions: {}
jobs:
  tests:
    strategy:
      matrix:
        target:
          # oldest 6.1 (which also have vmlinux file)
          # - kernelctf lts-6.1.35
          # 6.1.35 hangs randomly at boot a lot, without any error
          - kernelctf lts-6.1.36
          # newest 6.1
          - kernelctf lts-6.1.81
          # oldest 6.6
          - kernelctf lts-6.6.23
          # newest 6.6
          #   release-date: 2025-01-10T12:00:00Z
          - kernelctf lts-6.6.69
          - kernelctf cos-105-17412.495.75
          - kernelctf cos-109-17800.372.84
          # active mitigations
          - kernelctf mitigation-v4-6.6
          - kernelctf mitigation-v3b-6.1.55

          # some middle releases
          #   release-date: 2024-07-31T12:00:00Z
          - kernelctf lts-6.6.42
          - kernelctf cos-105-17412.370.75
          - kernelctf cos-109-17800.218.76
          #   release-date: 2024-01-12T12:00:00Z
          - kernelctf lts-6.1.70
          - kernelctf cos-105-17412.226.52
          - kernelctf cos-97-16919.404.26
      fail-fast: false # do not cancel test of other targets
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      target: ${{matrix.target}}
      silence_notifications: true

  summary:
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Send Google Chat Notification (on failure)
        if: ${{ needs.tests.result != 'success' }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_EXPKIT }}
        run: node ./.github/scripts/send_notification.js
