name: Run daily tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions: {}
jobs:
  tests:
    strategy:
      matrix:
        target: ["kernelctf lts-6.1.31", "kernelctf lts-6.1.81"]
      fail-fast: false # do not cancel test of other targets
    uses: ./.github/workflows/run-tests.yml
    secrets: inherit
    with:
      target: ${{matrix.target}}
