name: 'DB: upgrade to new config'
on:
  workflow_dispatch:
permissions: {}
jobs:
  upgrade_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.DB_GCS_SA_KEY }}'

      - name: Install kpwn_db prerequisites
        working-directory: kpwn_db
        run: pip install -r requirements.txt

      - name: Upgrade DB
        working-directory: scripts
        run: ./db_upgrade_config.sh
