name: Build and release libxdk
on:
  push:
    tags:
      - 'libxdk/v*.*.*' # Trigger on tags like libxdk/v1.0.0, libxdk/v1.2.3, libxdk/v1.0.0-beta, etc but not for xdk_dev/v1.0.0
jobs:
  build_and_release:
    runs-on: ubuntu-18.04 # For older ABI compatibility
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install C++ compiler (GCC 11 for compatibility)
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends g++-11 cmake
          # Set default compiler to GCC 11 for this job
          echo "CC=/usr/bin/gcc-11" >> $GITHUB_ENV
          echo "CXX=/usr/bin/g++-11" >> $GITHUB_ENV

      - name: Configure CMake for static build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DBUILD_SHARED_LIBS=OFF

      - name: Build the libxdk library
        run: cmake --build build -j$(nproc)

      - name: Package artifacts
        run: |
          PACKAGE_DIR="libxdk-${{ github.ref_name }}"
          mkdir -p "$PACKAGE_DIR/lib"
          mkdir -p "$PACKAGE_DIR/include/xdk"

          cp build/libkernelXDK.a "$PACKAGE_DIR/lib/libxdk.a"
          cp -R include/kernelXDK/. "$PACKAGE_DIR/include/xdk/"

          tar -czvf "libxdk-${{ github.ref_name }}.tar.gz" "$PACKAGE_DIR/"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "libxdk-${{ github.ref_name }}.tar.gz"
          name: Release ${{ github.ref_name }} # e.g. "Release v1.0.0"
          tag_name: ${{ github.ref_name }} # Associate with the pushed tag
          draft: true
          prerelease: true
          body: |
            Automated build for libxdk version ${{ github.ref_name }}

            This release provides the `libxdk.a` static library and public headers for Linux, built with GCC 11 on Ubuntu 18.04.

            **Contents:**
            - `lib/libxdk.a`: The static library.
            - `include/xdk/`: All public header files.

            See the commit history for detailed changes.
