name: Run tests
on:
  push:
    paths:
     - 'kpwn_db/**'
     - 'expkit/**'
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install Linux package prerequisites
        run: sudo apt-get update && sudo apt install -yq --no-install-recommends build-essential flex bison bc ca-certificates libelf-dev libssl-dev cpio pahole qemu-system-x86 libkeyutils-dev

      - name: Install tool prerequisites
        run: |
          cd kpwn_db
          pip install -r requirements.txt

      - name: Download cached kpwn module # to skip compilation and speedup tests
        run: curl https://storage.googleapis.com/kernel-research/pwnkit/kpwn_lts6181_v1.tar --create-dirs -o kernel-image-db/releases/kernelctf/lts-6.1.81/custom_modules.tar

      - name: Test kpwn_db
        if: ${{ success() || failure() }}
        working-directory: ./kpwn_db
        run: ./test.sh

      - name: Test expkit (local tests only)
        if: ${{ success() || failure() }}
        working-directory: ./expkit
        run: "make test && bin/test --test-suites StaticTests --tests ^TODO"

      - name: Test expkit (QEMU)
        if: ${{ success() || failure() }}
        working-directory: ./expkit
        run: CUSTOM_MODULES_KEEP=1 ./run_tests.sh --tests ^TODO

      - name: Test expkit samples
        if: ${{ success() || failure() }}
        working-directory: ./expkit
        run: CUSTOM_MODULES_KEEP=1 make -C samples/stack_pivot_and_rop test

      - name: Test expkit (local TODO tests only)
        if: ${{ success() || failure() }}
        continue-on-error: true
        working-directory: ./expkit
        run: "make test && bin/test --test-suites StaticTests --tests TODO"

      - name: Test expkit (QEMU TODO tests only)
        if: ${{ success() || failure() }}
        continue-on-error: true
        working-directory: ./expkit
        run: CUSTOM_MODULES_KEEP=1 ./run_tests.sh --test-suites RuntimeTests --tests TODO

      - name: Send Google Chat Notification (on failure)
        if: failure()
        uses: actions/github-script@v6
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_EXPKIT }}
        with:
          script: |
            const url = `https://github.com/google/kernel-research/actions/runs/${context.runId}`;
            const pp = context.payload;

            let title = "???";
            if (pp.pull_request)
              title = `PR #${pp.pull_request.number} ("${pp.pull_request.title}")`;
            else if (pp.head_commit)
              title = `commit ${pp.head_commit.id.substr(0,7)} ("${pp.head_commit.message}")`;

            await fetch(process.env.WEBHOOK_URL, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                "text": `*GHA FAIL*: workflow <${url}|${context.workflow}> failed for ${title} by ${context.actor}`
              })
            });
