name: Update target db
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions: {}
jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{secrets.DB_GCS_SA_KEY}}'

      - name: Install Linux package prerequisites
        run: sudo apt-get update && sudo apt install -yq --no-install-recommends pahole python3-ropgadget qemu-system-x86

      - name: Install rp++
        run: |
          wget https://github.com/0vercl0k/rp/releases/download/v2.1.3/rp-lin-gcc.zip
          unzip rp-lin-gcc.zip
          mv ./rp-lin rp++
          chmod u+x rp++
          echo "$PWD" >> "$GITHUB_PATH"

      - name: Install kpwn_db prerequisites
        working-directory: kpwn_db
        run: pip install -r requirements.txt

      - name: Install kernel_rop_generator prerequisites
        working-directory: kernel_rop_generator
        run: pip install -r requirements.txt

      - name: Update db
        working-directory: ./scripts
        run: ./update_kpwn_db.sh --auto-cleanup

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: 'scripts/*.txt'
